%YAML:1.0
rotationDegrees: 0
cannyThreshold1: 90
cannyThreshold2: 150
digitMinHeight: 24
digitMaxHeight: 35
digitYAlignment: 15
ocrMaxDist: 500000.
trainingDataFilename: "trainctr.yml"
whiteTreshold: 120
