%YAML:1.0
trainingDataFilename: "trainctr.yml"
meterDataFilename: "emeter.txt"
logFilename: "emeter.log"
meterValueMask: "^[12][0-9]{5}[0-9?]?$"
meterValueLength: 6
meterValueDecimals: 0
meterMaxPower: 50.
meterWindow: 13
rotationDegrees: 0
cannyThreshold1: 100
cannyThreshold2: 170
digitMinHeight: 24
digitMaxHeight: 35
digitYAlignment: 15
ocrMaxDist: 400000.
whiteTreshold: 120
