%YAML:1.0
rotationDegrees: 0
cannyThreshold1: 90
cannyThreshold2: 160
digitMinHeight: 25
digitMaxHeight: 35
digitYAlignment: 15
ocrMaxDist: 100000.
trainingDataFilename: "trainctr.yml"
whiteTreshold: 100
